name: farnfond
description: 'A new Flutter project.'
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: '>=3.4.1 <4.0.0'
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  get: ^4.6.6
  google_fonts: ^6.2.1
  introduction_screen: ^3.1.14
  get_storage: ^2.1.1
  draggable_home: ^1.0.5
  google_maps_flutter: ^2.7.0
  interactive_bottom_sheet: ^1.0.0
  permission_handler: ^11.3.1
  disable_battery_optimization: ^1.1.1
  geolocator: ^12.0.0
  firebase_core: ^2.24.2
  sliding_up_panel: ^2.0.0+1
  cloud_firestore: ^4.14.0
  firebase_auth: ^4.16.0
  firebase_storage: ^11.7.7
  flip_card: ^0.7.0
  uuid: ^4.4.0
  clickable_widget: ^0.0.5
  flutter_launcher_icons: ^0.13.1
  flutter_native_splash: ^2.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
flutter:
  uses-material-design: true
  assets:
    - assets/

flutter_launcher_icons:
  android: 'launcher_icon'
  ios: true
  image_path: 'assets/far_n_fond.png'
  min_sdk_android: 21 # android min sdk min:16, default 21
