name: farnfond
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: '>=3.4.1 <4.0.0'
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  firebase_core: ^3.0.0
  get: ^4.6.6
  google_fonts: ^6.2.1
  introduction_screen: ^3.1.14
  get_storage: ^2.1.1
  draggable_home: ^1.0.5
  google_maps_flutter: ^2.7.0
  interactive_bottom_sheet: ^1.0.0
  permission_handler: ^11.3.1
  disable_battery_optimization: ^1.1.1
  geolocator: ^12.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
flutter:
  uses-material-design: true
  assets:
    - assets/
